ALTER TABLE users
ADD COLUMN avatar_id TINYINT NOT NULL DEFAULT 1 COMMENT '1, 2, or 3 — maps to preset image',
ADD COLUMN games_played INT UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN games_won INT UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN games_lost INT UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN games_drawn INT UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN games_forfeited INT UNSIGNED NOT NULL DEFAULT 0;